# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DailySearch' do
    pod 'RxSwift', '5'
    pod 'RxCocoa', '5'
    pod 'SnapKit', '4.2.0', :inhibit_warnings => true
    pod 'ObjectMapper', '3.5.1'
    pod 'SwiftyJSON', '4.0'
    pod 'Alamofire', '4.9.1'
    pod 'Kingfisher', '4.10.1', :inhibit_warnings => true

  target 'DailySearchTests' do
    inherit! :search_paths
    pod 'RxBlocking', '5'
    pod 'RxTest', '5'
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
end
